# Generated by Django 4.0.3 on 2022-03-27 11:40

import commoninfo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('unique_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text="Enter patient's first name: ", max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')])),
                ('date_of_birth', models.DateField(validators=[commoninfo.models.validate_birthyear])),
                ('address', models.CharField(help_text="Enter the first line of patient's address: ", max_length=40)),
                ('city', models.CharField(default='null', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')])),
                ('state', models.CharField(default='null', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')])),
                ('postcode', models.CharField(default='null', max_length=8)),
                ('phone', models.CharField(help_text="Enter the patient's phone number: ", max_length=14, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Phone number should only contain numbers.')])),
                ('email', models.EmailField(blank='True', help_text="Enter the patient's email address: ", max_length=50)),
            ],
            options={
                'ordering': ['unique_id', 'first_name', 'last_name', 'date_of_birth', 'address', 'postcode', 'phone', 'email'],
            },
        ),
    ]
