# Generated by Django 4.0.3 on 2022-03-27 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postcode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
