# Generated by Django 4.0.3 on 2022-03-27 13:31

import commoninfo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0002_alter_patient_city_alter_patient_postcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['unique_id', 'first_name', 'last_name', 'date_of_birth', 'street', 'postcode', 'phone', 'email']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='In the form YYYY-MM-DD', validators=[commoninfo.models.validate_birthyear]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Phone number should only contain numbers.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'This field should only contain letters.')]),
        ),
    ]
