# Generated by Django 4.0.3 on 2022-03-27 13:32

import commoninfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0003_alter_patient_options_remove_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='(YYYY-MM-DD)', validators=[commoninfo.models.validate_birthyear]),
        ),
    ]
