# Generated by Django 4.0.3 on 2022-03-27 13:35

import commoninfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0004_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(help_text='YYYY-MM-DD', validators=[commoninfo.models.validate_birthyear]),
        ),
    ]
