# Generated by Django 4.0.3 on 2022-04-03 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commoninfo', '0006_alter_patient_city_alter_patient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Phone number should only contain numbers.')]),
        ),
    ]
